# Compiler
CC = g++

# Compiler flags
CFLAGS = -Wall -Werror

# Directories
SRC_DIR = # TODO
BUILD_DIR = # TODO

# Source files
SRCS = # TODO

# Object files
OBJS = # TODO

# Target executable
TARGET = main

# Default target
all: $(TARGET)

# TODO: Compile source files into object files


# TODO: Compile main file into object file


# TODO: Link object files into target executable

# Clean build directory
clean:
	rm -rf  # TODO
